export  {default as App} from './App'
export  {default as Posts} from './Posts'
export  {default as NavBar} from './NavBar'
export  {default as Login} from './Login'
export  {default as Profile} from './Profile'
export  {default as Register} from './Register'
export  {default as ModPost} from './ModPost'
export  {default as NewPost} from './NewPost'